name: build image

on:
  push:
    branches: [ example ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: configurar python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: instalar dependencias
      run:pip install flask

    - name: login a Github packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ Github.actor}}
        password: ${{ secrets.GITHUB_TOKEN}}


    - name: construir y publicar imagen
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ Github.repository_owner }}/python_app:latest